/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShapesRouteImport } from './routes/shapes'
import { Route as NumbersRouteImport } from './routes/numbers'
import { Route as LettersRouteImport } from './routes/letters'
import { Route as FlashcardsRouteImport } from './routes/flashcards'
import { Route as ColorsRouteImport } from './routes/colors'
import { Route as IndexRouteImport } from './routes/index'

const ShapesRoute = ShapesRouteImport.update({
  id: '/shapes',
  path: '/shapes',
  getParentRoute: () => rootRouteImport,
} as any)
const NumbersRoute = NumbersRouteImport.update({
  id: '/numbers',
  path: '/numbers',
  getParentRoute: () => rootRouteImport,
} as any)
const LettersRoute = LettersRouteImport.update({
  id: '/letters',
  path: '/letters',
  getParentRoute: () => rootRouteImport,
} as any)
const FlashcardsRoute = FlashcardsRouteImport.update({
  id: '/flashcards',
  path: '/flashcards',
  getParentRoute: () => rootRouteImport,
} as any)
const ColorsRoute = ColorsRouteImport.update({
  id: '/colors',
  path: '/colors',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/colors': typeof ColorsRoute
  '/flashcards': typeof FlashcardsRoute
  '/letters': typeof LettersRoute
  '/numbers': typeof NumbersRoute
  '/shapes': typeof ShapesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/colors': typeof ColorsRoute
  '/flashcards': typeof FlashcardsRoute
  '/letters': typeof LettersRoute
  '/numbers': typeof NumbersRoute
  '/shapes': typeof ShapesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/colors': typeof ColorsRoute
  '/flashcards': typeof FlashcardsRoute
  '/letters': typeof LettersRoute
  '/numbers': typeof NumbersRoute
  '/shapes': typeof ShapesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/colors'
    | '/flashcards'
    | '/letters'
    | '/numbers'
    | '/shapes'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/colors' | '/flashcards' | '/letters' | '/numbers' | '/shapes'
  id:
    | '__root__'
    | '/'
    | '/colors'
    | '/flashcards'
    | '/letters'
    | '/numbers'
    | '/shapes'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ColorsRoute: typeof ColorsRoute
  FlashcardsRoute: typeof FlashcardsRoute
  LettersRoute: typeof LettersRoute
  NumbersRoute: typeof NumbersRoute
  ShapesRoute: typeof ShapesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/shapes': {
      id: '/shapes'
      path: '/shapes'
      fullPath: '/shapes'
      preLoaderRoute: typeof ShapesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/numbers': {
      id: '/numbers'
      path: '/numbers'
      fullPath: '/numbers'
      preLoaderRoute: typeof NumbersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/letters': {
      id: '/letters'
      path: '/letters'
      fullPath: '/letters'
      preLoaderRoute: typeof LettersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flashcards': {
      id: '/flashcards'
      path: '/flashcards'
      fullPath: '/flashcards'
      preLoaderRoute: typeof FlashcardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/colors': {
      id: '/colors'
      path: '/colors'
      fullPath: '/colors'
      preLoaderRoute: typeof ColorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ColorsRoute: ColorsRoute,
  FlashcardsRoute: FlashcardsRoute,
  LettersRoute: LettersRoute,
  NumbersRoute: NumbersRoute,
  ShapesRoute: ShapesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
