/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as NumbersRouteImport } from './routes/numbers'
import { Route as LettersRouteImport } from './routes/letters'
import { Route as ColorsRouteImport } from './routes/colors'
import { Route as IndexRouteImport } from './routes/index'

const NumbersRoute = NumbersRouteImport.update({
  id: '/numbers',
  path: '/numbers',
  getParentRoute: () => rootRouteImport,
} as any)
const LettersRoute = LettersRouteImport.update({
  id: '/letters',
  path: '/letters',
  getParentRoute: () => rootRouteImport,
} as any)
const ColorsRoute = ColorsRouteImport.update({
  id: '/colors',
  path: '/colors',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/colors': typeof ColorsRoute
  '/letters': typeof LettersRoute
  '/numbers': typeof NumbersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/colors': typeof ColorsRoute
  '/letters': typeof LettersRoute
  '/numbers': typeof NumbersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/colors': typeof ColorsRoute
  '/letters': typeof LettersRoute
  '/numbers': typeof NumbersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/colors' | '/letters' | '/numbers'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/colors' | '/letters' | '/numbers'
  id: '__root__' | '/' | '/colors' | '/letters' | '/numbers'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ColorsRoute: typeof ColorsRoute
  LettersRoute: typeof LettersRoute
  NumbersRoute: typeof NumbersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/numbers': {
      id: '/numbers'
      path: '/numbers'
      fullPath: '/numbers'
      preLoaderRoute: typeof NumbersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/letters': {
      id: '/letters'
      path: '/letters'
      fullPath: '/letters'
      preLoaderRoute: typeof LettersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/colors': {
      id: '/colors'
      path: '/colors'
      fullPath: '/colors'
      preLoaderRoute: typeof ColorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ColorsRoute: ColorsRoute,
  LettersRoute: LettersRoute,
  NumbersRoute: NumbersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
