// AUTO-GENERATED by scripts/build-sprite-manifest.mjs - do not hand-edit.
// Regenerate with: `node scripts/build-sprite-manifest.mjs` (uses existing audio files)
// or `node scripts/generate-tts-sprites.mjs` (re-runs TTS, then rebuilds).
//
// Every sprite topic exposes one entry per supported locale. The runtime
// resolves the current locale via i18next and falls back to "en" when a
// VI asset has not been generated yet.

import type { ColorId } from "@/data/colors";
import type { ShapeId } from "@/data/shapes";

export type SpriteLocale = "en" | "vi";

export interface AudioSegment {
  start: number;
  end: number;
}

export interface AudioSpriteLocale {
  src: string;
  duration: number;
  sampleRate: number;
  segments: AudioSegment[];
}

export type AudioSprite = Partial<Record<SpriteLocale, AudioSpriteLocale>>;

export const AUDIO_SPRITES = {
  numbers: {
    vi: {
      src: "assets/audio/numbers-vi.mp3",
      duration: 115.128,
      sampleRate: 22050,
      segments: [{"start":0.09,"end":0.751},{"start":1.561,"end":2.372},{"start":3.152,"end":3.903},{"start":4.684,"end":5.494},{"start":6.275,"end":6.995},{"start":7.776,"end":9.037},{"start":9.817,"end":11.108},{"start":11.889,"end":13.3},{"start":14.081,"end":15.312},{"start":16.092,"end":17.323},{"start":18.104,"end":19.665},{"start":20.476,"end":21.977},{"start":22.787,"end":24.378},{"start":25.159,"end":26.72},{"start":27.501,"end":29.032},{"start":29.843,"end":31.494},{"start":32.304,"end":33.956},{"start":34.766,"end":36.508},{"start":37.288,"end":38.969},{"start":39.75,"end":41.221},{"start":42.032,"end":43.683},{"start":44.494,"end":46.205},{"start":47.016,"end":48.817},{"start":49.598,"end":51.249},{"start":52.029,"end":53.5},{"start":54.281,"end":55.902},{"start":56.713,"end":58.334},{"start":59.145,"end":60.856},{"start":61.637,"end":63.198},{"start":64.008,"end":65.449},{"start":66.35,"end":67.941},{"start":68.812,"end":70.433},{"start":71.304,"end":72.955},{"start":73.826,"end":75.477},{"start":76.318,"end":77.789},{"start":78.599,"end":80.281},{"start":81.091,"end":82.802},{"start":83.613,"end":85.444},{"start":86.225,"end":87.966},{"start":88.747,"end":90.308},{"start":91.119,"end":92.65},{"start":93.491,"end":95.112},{"start":95.922,"end":97.694},{"start":98.474,"end":100.036},{"start":100.846,"end":102.287},{"start":103.098,"end":104.629},{"start":105.44,"end":107.151},{"start":107.962,"end":109.703},{"start":110.483,"end":112.135},{"start":112.945,"end":114.326}],
    },
    en: {
      src: "assets/audio/numbers-en.mp3",
      duration: 131.352,
      sampleRate: 22050,
      segments: [{"start":0.12,"end":0.54},{"start":0.661,"end":1.081},{"start":2.012,"end":2.432},{"start":2.582,"end":3.002},{"start":3.933,"end":5.194},{"start":6.005,"end":7.025},{"start":7.956,"end":9.007},{"start":9.847,"end":11.168},{"start":12.129,"end":13.63},{"start":14.531,"end":16.272},{"start":17.113,"end":18.764},{"start":19.605,"end":21.076},{"start":21.887,"end":23.748},{"start":24.559,"end":26.51},{"start":27.321,"end":28.221},{"start":28.401,"end":29.452},{"start":30.233,"end":32.124},{"start":32.995,"end":33.986},{"start":34.136,"end":34.646},{"start":35.487,"end":36.267},{"start":36.448,"end":37.228},{"start":38.099,"end":38.939},{"start":39.15,"end":39.96},{"start":40.801,"end":41.611},{"start":41.822,"end":42.782},{"start":43.653,"end":44.584},{"start":44.794,"end":45.454},{"start":46.385,"end":47.886},{"start":48.787,"end":50.528},{"start":51.459,"end":52.299},{"start":52.45,"end":53.29},{"start":54.191,"end":55.001},{"start":55.152,"end":56.142},{"start":57.013,"end":58.004},{"start":58.124,"end":58.844},{"start":59.805,"end":61.366},{"start":62.237,"end":64.008},{"start":64.909,"end":65.81},{"start":65.93,"end":66.8},{"start":67.671,"end":68.542},{"start":68.692,"end":69.713},{"start":70.553,"end":71.544},{"start":71.664,"end":72.415},{"start":73.345,"end":75.027},{"start":75.867,"end":77.879},{"start":78.72,"end":80.851},{"start":81.692,"end":83.973},{"start":84.814,"end":86.916},{"start":87.816,"end":89.648},{"start":90.518,"end":92.59},{"start":93.431,"end":95.592},{"start":96.433,"end":97.454},{"start":97.574,"end":98.745},{"start":99.555,"end":101.717},{"start":102.618,"end":104.149},{"start":104.989,"end":106.55},{"start":107.391,"end":109.072},{"start":109.883,"end":111.684},{"start":112.495,"end":114.146},{"start":115.017,"end":116.458},{"start":117.299,"end":119.13},{"start":119.971,"end":121.952},{"start":122.793,"end":123.723},{"start":123.874,"end":124.954},{"start":125.765,"end":127.716},{"start":128.587,"end":130.479}],
    },
  },
  colors: {
    vi: {
      src: "assets/audio/colors-vi.mp3",
      duration: 15.48,
      sampleRate: 22050,
      segments: [{"start":0.09,"end":0.57},{"start":1.591,"end":2.102},{"start":3.182,"end":3.843},{"start":4.804,"end":5.164},{"start":6.095,"end":6.515},{"start":7.476,"end":7.926},{"start":8.887,"end":9.277},{"start":10.268,"end":10.658},{"start":11.619,"end":12.009},{"start":13.03,"end":13.39},{"start":14.351,"end":14.681}],
    },
    en: {
      src: "assets/audio/colors-en.mp3",
      duration: 15.168,
      sampleRate: 22050,
      segments: [{"start":0.12,"end":0.51},{"start":1.381,"end":1.921},{"start":2.762,"end":3.212},{"start":4.083,"end":4.473},{"start":5.374,"end":5.794},{"start":6.815,"end":7.386},{"start":8.226,"end":8.887},{"start":9.727,"end":10.088},{"start":11.048,"end":11.619},{"start":12.429,"end":12.91},{"start":13.75,"end":14.351}],
    },
  },
  shapes: {
    vi: {
      src: "assets/audio/shapes-vi.mp3",
      duration: 14.184,
      sampleRate: 22050,
      segments: [{"start":0.12,"end":0.781},{"start":1.741,"end":2.552},{"start":3.573,"end":4.443},{"start":5.374,"end":6.095},{"start":7.055,"end":7.896},{"start":8.887,"end":9.817},{"start":10.778,"end":11.739},{"start":12.7,"end":13.36}],
    },
    en: {
      src: "assets/audio/shapes-en.mp3",
      duration: 12.312,
      sampleRate: 22050,
      segments: [{"start":0.12,"end":0.72},{"start":1.591,"end":2.492},{"start":3.303,"end":4.173},{"start":5.014,"end":5.704},{"start":6.515,"end":7.085},{"start":7.956,"end":8.586},{"start":9.427,"end":9.847},{"start":10.808,"end":11.499}],
    },
  },
  alphabet: {
    vi: {
      src: "assets/audio/alphabet-vi.mp3",
      duration: 34.896,
      sampleRate: 22050,
      segments: [{"start":0.12,"end":1.261},{"start":2.252,"end":2.882},{"start":3.843,"end":4.443},{"start":5.434,"end":6.545},{"start":7.536,"end":8.166},{"start":9.157,"end":9.697},{"start":10.658,"end":11.739},{"start":12.73,"end":13.33},{"start":14.291,"end":14.921},{"start":15.912,"end":16.572},{"start":17.593,"end":18.254},{"start":19.245,"end":20.445},{"start":21.406,"end":22.007},{"start":22.967,"end":23.628},{"start":24.619,"end":25.159},{"start":26.12,"end":26.75},{"start":27.711,"end":28.822},{"start":29.813,"end":30.623},{"start":31.584,"end":32.064},{"start":33.025,"end":34.076}],
    },
    en: {
      src: "assets/audio/alphabet-en.mp3",
      duration: 14.28,
      sampleRate: 22050,
      segments: [{"start":0.09,"end":0.42},{"start":0.6,"end":1.471},{"start":1.621,"end":2.402},{"start":2.522,"end":2.882},{"start":3.062,"end":5.014},{"start":5.134,"end":6.545},{"start":6.695,"end":7.596},{"start":7.716,"end":8.076},{"start":8.226,"end":8.677},{"start":8.797,"end":9.637},{"start":9.757,"end":10.178},{"start":10.298,"end":11.078},{"start":11.199,"end":13.42}],
    },
  },
  alphabetWords: {
    en: {
      src: "assets/audio/alphabet-words-en.mp3",
      duration: 37.176,
      sampleRate: 22050,
      segments: [{"start":0.09,"end":0.63},{"start":1.471,"end":1.951},{"start":2.822,"end":3.242},{"start":4.143,"end":4.593},{"start":5.434,"end":6.215},{"start":7.085,"end":7.626},{"start":8.406,"end":8.827},{"start":9.757,"end":10.358},{"start":11.168,"end":12.039},{"start":12.85,"end":13.42},{"start":14.261,"end":14.681},{"start":15.582,"end":16.152},{"start":16.963,"end":17.593},{"start":18.404,"end":18.914},{"start":19.785,"end":20.475},{"start":21.286,"end":21.917},{"start":22.757,"end":23.268},{"start":24.108,"end":24.649},{"start":25.549,"end":26.21},{"start":27.05,"end":27.501},{"start":28.311,"end":29.122},{"start":29.993,"end":30.533},{"start":31.344,"end":31.854},{"start":32.665,"end":33.415},{"start":34.256,"end":34.856},{"start":35.697,"end":36.357}],
    },
    vi: {
      src: "assets/audio/alphabet-words-vi.mp3",
      duration: 40.752,
      sampleRate: 22050,
      segments: [{"start":0.09,"end":0.72},{"start":1.651,"end":2.282},{"start":3.242,"end":3.873},{"start":4.864,"end":5.554},{"start":6.515,"end":7.175},{"start":8.136,"end":8.797},{"start":9.727,"end":10.388},{"start":11.349,"end":11.979},{"start":13,"end":13.66},{"start":14.651,"end":15.342},{"start":16.302,"end":16.963},{"start":17.954,"end":18.944},{"start":19.905,"end":20.596},{"start":21.556,"end":22.217},{"start":23.178,"end":23.838},{"start":24.799,"end":25.339},{"start":26.27,"end":27.05},{"start":28.011,"end":28.732},{"start":29.692,"end":30.383},{"start":31.374,"end":31.974},{"start":32.965,"end":34.256},{"start":35.247,"end":35.817},{"start":36.808,"end":37.979},{"start":38.969,"end":39.96}],
    },
  },
  prompts: {
    en: {
      src: "assets/audio/prompts-en.mp3",
      duration: 26.592,
      sampleRate: 22050,
      segments: [{"start":0.09,"end":1.321},{"start":2.132,"end":4.233},{"start":5.164,"end":6.635},{"start":7.536,"end":8.887},{"start":9.697,"end":11.349},{"start":12.159,"end":13.45},{"start":14.291,"end":15.702},{"start":16.513,"end":17.863},{"start":18.674,"end":20.025},{"start":20.836,"end":22.127},{"start":22.967,"end":23.538},{"start":24.408,"end":25.759}],
    },
    vi: {
      src: "assets/audio/prompts-vi.mp3",
      duration: 25.464,
      sampleRate: 22050,
      segments: [{"start":0.09,"end":1.411},{"start":2.402,"end":4.143},{"start":5.134,"end":6.665},{"start":7.626,"end":8.797},{"start":9.817,"end":11.138},{"start":11.949,"end":13.09},{"start":14.051,"end":15.221},{"start":16.212,"end":17.563},{"start":18.554,"end":19.695},{"start":20.686,"end":21.826},{"start":22.817,"end":23.478},{"start":23.598,"end":24.649}],
    },
  },
} satisfies Record<string, AudioSprite>;

export type SpriteTopic = keyof typeof AUDIO_SPRITES;

export type PromptKey =
  | "counting"
  | "alphabetGame"
  | "sequence"
  | "colorGuess"
  | "colorMatching"
  | "shapesGame"
  | "flashcardNumber"
  | "flashcardLetter"
  | "flashcardColor"
  | "flashcardShape"
  | "preview";

// Per-locale index maps. EN keeps the legacy hand-tuned offsets (intro at
// index 0 for alphabet, hand-picked takes for colors/shapes); VI uses the
// content order from the TTS spec (0-based).
export const LETTER_SPRITE_INDEX: Record<SpriteLocale, Partial<Record<string, number>>> = {"en":{"A":0,"B":1,"C":2,"D":3,"E":4,"F":5,"G":6,"H":7,"I":8,"J":9,"K":10,"L":11,"M":12,"N":13,"O":14,"P":15,"Q":16,"R":17,"S":18,"T":19,"U":20,"V":21,"W":22,"X":23,"Y":24,"Z":25},"vi":{"A":0,"B":1,"C":2,"D":3,"E":4,"F":5,"G":6,"H":7,"I":8,"J":9,"K":10,"L":11,"M":12,"N":13,"O":14,"P":15,"Q":16,"R":17,"S":18,"T":19,"U":20,"V":21,"W":22,"X":23,"Y":24,"Z":25}};

export const NUMBER_SPRITE_INDEX: Record<SpriteLocale, Partial<Record<number, number>>> = {"en":{"1":0,"2":1,"3":2,"4":3,"5":4,"6":5,"7":6,"8":7,"9":8,"10":9,"11":10,"12":11,"13":12,"14":13,"15":14,"16":15,"17":16,"18":17,"19":18,"20":19,"21":20,"22":21,"23":22,"24":23,"25":24,"26":25,"27":26,"28":27,"29":28,"30":29,"31":30,"32":31,"33":32,"34":33,"35":34,"36":35,"37":36,"38":37,"39":38,"40":39,"41":40,"42":41,"43":42,"44":43,"45":44,"46":45,"47":46,"48":47,"49":48,"50":49,"51":50,"52":51,"53":52,"54":53,"55":54,"56":55,"57":56,"58":57,"59":58,"60":59,"61":60,"62":61,"63":62,"64":63,"65":64,"66":65,"67":66,"68":67,"69":68,"70":69,"71":70,"72":71,"73":72,"74":73,"75":74,"76":75,"77":76,"78":77,"79":78,"80":79,"81":80,"82":81,"83":82,"84":83,"85":84,"86":85,"87":86,"88":87,"89":88,"90":89,"91":90,"92":91,"93":92,"94":93,"95":94,"96":95,"97":96,"98":97,"99":98,"100":99},"vi":{"1":0,"2":1,"3":2,"4":3,"5":4,"6":5,"7":6,"8":7,"9":8,"10":9,"11":10,"12":11,"13":12,"14":13,"15":14,"16":15,"17":16,"18":17,"19":18,"20":19,"21":20,"22":21,"23":22,"24":23,"25":24,"26":25,"27":26,"28":27,"29":28,"30":29,"31":30,"32":31,"33":32,"34":33,"35":34,"36":35,"37":36,"38":37,"39":38,"40":39,"41":40,"42":41,"43":42,"44":43,"45":44,"46":45,"47":46,"48":47,"49":48,"50":49,"51":50,"52":51,"53":52,"54":53,"55":54,"56":55,"57":56,"58":57,"59":58,"60":59,"61":60,"62":61,"63":62,"64":63,"65":64,"66":65,"67":66,"68":67,"69":68,"70":69,"71":70,"72":71,"73":72,"74":73,"75":74,"76":75,"77":76,"78":77,"79":78,"80":79,"81":80,"82":81,"83":82,"84":83,"85":84,"86":85,"87":86,"88":87,"89":88,"90":89,"91":90,"92":91,"93":92,"94":93,"95":94,"96":95,"97":96,"98":97,"99":98,"100":99}};

export const COLOR_SPRITE_INDEX: Record<SpriteLocale, Partial<Record<ColorId, number>>> = {"en":{"red":0,"yellow":1,"green":2,"blue":3,"purple":4,"orange":5,"pink":6,"brown":7,"black":8,"white":9,"gray":10},"vi":{"red":0,"green":1,"blue":2,"white":3,"black":4,"yellow":5,"orange":6,"pink":7,"brown":8,"gray":9,"purple":10}};

export const SHAPE_SPRITE_INDEX: Record<SpriteLocale, Partial<Record<ShapeId, number>>> = {"en":{"circle":0,"square":1,"triangle":2,"rectangle":3,"star":4,"heart":5,"diamond":6,"oval":7},"vi":{"square":0,"rectangle":1,"triangle":2,"circle":3,"oval":4,"star":5,"heart":6,"diamond":7}};

export const PROMPT_SPRITE_INDEX: Record<SpriteLocale, Record<PromptKey, number>> = {"en":{"counting":0,"alphabetGame":1,"sequence":2,"colorGuess":3,"colorMatching":4,"shapesGame":5,"flashcardNumber":6,"flashcardLetter":7,"flashcardColor":8,"flashcardShape":9,"preview":10},"vi":{"counting":0,"alphabetGame":1,"sequence":2,"colorGuess":3,"colorMatching":4,"shapesGame":5,"flashcardNumber":6,"flashcardLetter":7,"flashcardColor":8,"flashcardShape":9,"preview":10}};

// Alphabet words ("Apple" for A, etc.) are recorded per locale.
export const ALPHABET_WORDS_SPRITE_INDEX: Record<SpriteLocale, Partial<Record<string, number>>> = {"en":{"A":0,"B":1,"C":2,"D":3,"E":4,"F":5,"G":6,"H":7,"I":8,"J":9,"K":10,"L":11,"M":12,"N":13,"O":14,"P":15,"Q":16,"R":17,"S":18,"T":19,"U":20,"V":21,"W":22,"X":23,"Y":24,"Z":25},"vi":{"A":0,"B":1,"C":2,"D":3,"E":4,"F":5,"G":6,"H":7,"I":8,"J":9,"K":10,"L":11,"M":12,"N":13,"O":14,"P":15,"Q":16,"R":17,"S":18,"T":19,"U":20,"V":21,"W":22,"X":23,"Y":24,"Z":25}};
